name: Use Secrets
on:
  push:
    paths:
      - ".github/workflows/use-secrets.yml"

jobs:
  check-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Grade use-secrets activity
      - uses: actions/checkout@v2

      - uses: ./.github/actions/check-secrets-action
        id: check-secrets
        with:
          secrets-context: ${{ toJSON(secrets) }}
          your-secret: ${{ secrets.EXERCISE_PAT }}
